[package]
name = "single-page-scraper"
version = "0.1.0"
edition = "2021"

[dependencies]
chrome = "0.1.0"
headless_chrome = "0.9.0"
rayon = "1.10.0"
reqwest = { version = "0.12.8", features = ["json"] }
scraper = "0.20.0"
tokio = { version = "1.0", features = ["full"] }
