[package]
name = "cloud-ai"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
select = "0.5"
url = "2.2"
rayon = "1.5"
scraper = "0.20.0"
playwright = "0.0.20"
tokio = { version = "1.42.0", features = ["full"] }
serde_json = "1.0.133"
