[package]
name = "my_rust_lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2", features = ["serde-json"] }
napi-build = "2.1.3"
napi-derive = "2"

[build-dependencies]
napi-build = "1"
